/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-05-20")
public class CreateQrCodeResponse implements org.apache.thrift.TBase<CreateQrCodeResponse, CreateQrCodeResponse._Fields>, java.io.Serializable, Cloneable, Comparable<CreateQrCodeResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CreateQrCodeResponse");

  private static final org.apache.thrift.protocol.TField CALLBACK_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("callbackUrl", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CreateQrCodeResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CreateQrCodeResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String callbackUrl; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CALLBACK_URL((short)1, "callbackUrl");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CALLBACK_URL
          return CALLBACK_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CALLBACK_URL, new org.apache.thrift.meta_data.FieldMetaData("callbackUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CreateQrCodeResponse.class, metaDataMap);
  }

  public CreateQrCodeResponse() {
  }

  public CreateQrCodeResponse(
    java.lang.String callbackUrl)
  {
    this();
    this.callbackUrl = callbackUrl;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CreateQrCodeResponse(CreateQrCodeResponse other) {
    if (other.isSetCallbackUrl()) {
      this.callbackUrl = other.callbackUrl;
    }
  }

  public CreateQrCodeResponse deepCopy() {
    return new CreateQrCodeResponse(this);
  }

  @Override
  public void clear() {
    this.callbackUrl = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCallbackUrl() {
    return this.callbackUrl;
  }

  public CreateQrCodeResponse setCallbackUrl(@org.apache.thrift.annotation.Nullable java.lang.String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  public void unsetCallbackUrl() {
    this.callbackUrl = null;
  }

  /** Returns true if field callbackUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetCallbackUrl() {
    return this.callbackUrl != null;
  }

  public void setCallbackUrlIsSet(boolean value) {
    if (!value) {
      this.callbackUrl = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CALLBACK_URL:
      if (value == null) {
        unsetCallbackUrl();
      } else {
        setCallbackUrl((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CALLBACK_URL:
      return getCallbackUrl();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CALLBACK_URL:
      return isSetCallbackUrl();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CreateQrCodeResponse)
      return this.equals((CreateQrCodeResponse)that);
    return false;
  }

  public boolean equals(CreateQrCodeResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_callbackUrl = true && this.isSetCallbackUrl();
    boolean that_present_callbackUrl = true && that.isSetCallbackUrl();
    if (this_present_callbackUrl || that_present_callbackUrl) {
      if (!(this_present_callbackUrl && that_present_callbackUrl))
        return false;
      if (!this.callbackUrl.equals(that.callbackUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCallbackUrl()) ? 131071 : 524287);
    if (isSetCallbackUrl())
      hashCode = hashCode * 8191 + callbackUrl.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CreateQrCodeResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCallbackUrl()).compareTo(other.isSetCallbackUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCallbackUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.callbackUrl, other.callbackUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CreateQrCodeResponse(");
    boolean first = true;

    sb.append("callbackUrl:");
    if (this.callbackUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.callbackUrl);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CreateQrCodeResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreateQrCodeResponseStandardScheme getScheme() {
      return new CreateQrCodeResponseStandardScheme();
    }
  }

  private static class CreateQrCodeResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<CreateQrCodeResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CreateQrCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CALLBACK_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.callbackUrl = iprot.readString();
              struct.setCallbackUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CreateQrCodeResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.callbackUrl != null) {
        oprot.writeFieldBegin(CALLBACK_URL_FIELD_DESC);
        oprot.writeString(struct.callbackUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CreateQrCodeResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreateQrCodeResponseTupleScheme getScheme() {
      return new CreateQrCodeResponseTupleScheme();
    }
  }

  private static class CreateQrCodeResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<CreateQrCodeResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CreateQrCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCallbackUrl()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCallbackUrl()) {
        oprot.writeString(struct.callbackUrl);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CreateQrCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.callbackUrl = iprot.readString();
        struct.setCallbackUrlIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

