/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-05-20")
public class CreatePinCodeResponse implements org.apache.thrift.TBase<CreatePinCodeResponse, CreatePinCodeResponse._Fields>, java.io.Serializable, Cloneable, Comparable<CreatePinCodeResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CreatePinCodeResponse");

  private static final org.apache.thrift.protocol.TField PIN_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("pinCode", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CreatePinCodeResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CreatePinCodeResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String pinCode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PIN_CODE((short)1, "pinCode");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PIN_CODE
          return PIN_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PIN_CODE, new org.apache.thrift.meta_data.FieldMetaData("pinCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CreatePinCodeResponse.class, metaDataMap);
  }

  public CreatePinCodeResponse() {
  }

  public CreatePinCodeResponse(
    java.lang.String pinCode)
  {
    this();
    this.pinCode = pinCode;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CreatePinCodeResponse(CreatePinCodeResponse other) {
    if (other.isSetPinCode()) {
      this.pinCode = other.pinCode;
    }
  }

  public CreatePinCodeResponse deepCopy() {
    return new CreatePinCodeResponse(this);
  }

  @Override
  public void clear() {
    this.pinCode = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPinCode() {
    return this.pinCode;
  }

  public CreatePinCodeResponse setPinCode(@org.apache.thrift.annotation.Nullable java.lang.String pinCode) {
    this.pinCode = pinCode;
    return this;
  }

  public void unsetPinCode() {
    this.pinCode = null;
  }

  /** Returns true if field pinCode is set (has been assigned a value) and false otherwise */
  public boolean isSetPinCode() {
    return this.pinCode != null;
  }

  public void setPinCodeIsSet(boolean value) {
    if (!value) {
      this.pinCode = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PIN_CODE:
      if (value == null) {
        unsetPinCode();
      } else {
        setPinCode((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PIN_CODE:
      return getPinCode();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PIN_CODE:
      return isSetPinCode();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CreatePinCodeResponse)
      return this.equals((CreatePinCodeResponse)that);
    return false;
  }

  public boolean equals(CreatePinCodeResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_pinCode = true && this.isSetPinCode();
    boolean that_present_pinCode = true && that.isSetPinCode();
    if (this_present_pinCode || that_present_pinCode) {
      if (!(this_present_pinCode && that_present_pinCode))
        return false;
      if (!this.pinCode.equals(that.pinCode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPinCode()) ? 131071 : 524287);
    if (isSetPinCode())
      hashCode = hashCode * 8191 + pinCode.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CreatePinCodeResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPinCode()).compareTo(other.isSetPinCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPinCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pinCode, other.pinCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CreatePinCodeResponse(");
    boolean first = true;

    sb.append("pinCode:");
    if (this.pinCode == null) {
      sb.append("null");
    } else {
      sb.append(this.pinCode);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CreatePinCodeResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreatePinCodeResponseStandardScheme getScheme() {
      return new CreatePinCodeResponseStandardScheme();
    }
  }

  private static class CreatePinCodeResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<CreatePinCodeResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CreatePinCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PIN_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pinCode = iprot.readString();
              struct.setPinCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CreatePinCodeResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pinCode != null) {
        oprot.writeFieldBegin(PIN_CODE_FIELD_DESC);
        oprot.writeString(struct.pinCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CreatePinCodeResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreatePinCodeResponseTupleScheme getScheme() {
      return new CreatePinCodeResponseTupleScheme();
    }
  }

  private static class CreatePinCodeResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<CreatePinCodeResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CreatePinCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPinCode()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPinCode()) {
        oprot.writeString(struct.pinCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CreatePinCodeResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.pinCode = iprot.readString();
        struct.setPinCodeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

