/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-05-20")
public class CreatePinCodeRequest implements org.apache.thrift.TBase<CreatePinCodeRequest, CreatePinCodeRequest._Fields>, java.io.Serializable, Cloneable, Comparable<CreatePinCodeRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CreatePinCodeRequest");

  private static final org.apache.thrift.protocol.TField AUTH_SESSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("authSessionId", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CreatePinCodeRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CreatePinCodeRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String authSessionId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AUTH_SESSION_ID((short)1, "authSessionId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AUTH_SESSION_ID
          return AUTH_SESSION_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AUTH_SESSION_ID, new org.apache.thrift.meta_data.FieldMetaData("authSessionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CreatePinCodeRequest.class, metaDataMap);
  }

  public CreatePinCodeRequest() {
  }

  public CreatePinCodeRequest(
    java.lang.String authSessionId)
  {
    this();
    this.authSessionId = authSessionId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CreatePinCodeRequest(CreatePinCodeRequest other) {
    if (other.isSetAuthSessionId()) {
      this.authSessionId = other.authSessionId;
    }
  }

  public CreatePinCodeRequest deepCopy() {
    return new CreatePinCodeRequest(this);
  }

  @Override
  public void clear() {
    this.authSessionId = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAuthSessionId() {
    return this.authSessionId;
  }

  public CreatePinCodeRequest setAuthSessionId(@org.apache.thrift.annotation.Nullable java.lang.String authSessionId) {
    this.authSessionId = authSessionId;
    return this;
  }

  public void unsetAuthSessionId() {
    this.authSessionId = null;
  }

  /** Returns true if field authSessionId is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthSessionId() {
    return this.authSessionId != null;
  }

  public void setAuthSessionIdIsSet(boolean value) {
    if (!value) {
      this.authSessionId = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case AUTH_SESSION_ID:
      if (value == null) {
        unsetAuthSessionId();
      } else {
        setAuthSessionId((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case AUTH_SESSION_ID:
      return getAuthSessionId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case AUTH_SESSION_ID:
      return isSetAuthSessionId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CreatePinCodeRequest)
      return this.equals((CreatePinCodeRequest)that);
    return false;
  }

  public boolean equals(CreatePinCodeRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_authSessionId = true && this.isSetAuthSessionId();
    boolean that_present_authSessionId = true && that.isSetAuthSessionId();
    if (this_present_authSessionId || that_present_authSessionId) {
      if (!(this_present_authSessionId && that_present_authSessionId))
        return false;
      if (!this.authSessionId.equals(that.authSessionId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAuthSessionId()) ? 131071 : 524287);
    if (isSetAuthSessionId())
      hashCode = hashCode * 8191 + authSessionId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CreatePinCodeRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAuthSessionId()).compareTo(other.isSetAuthSessionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthSessionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authSessionId, other.authSessionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CreatePinCodeRequest(");
    boolean first = true;

    sb.append("authSessionId:");
    if (this.authSessionId == null) {
      sb.append("null");
    } else {
      sb.append(this.authSessionId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CreatePinCodeRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreatePinCodeRequestStandardScheme getScheme() {
      return new CreatePinCodeRequestStandardScheme();
    }
  }

  private static class CreatePinCodeRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<CreatePinCodeRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CreatePinCodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // AUTH_SESSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.authSessionId = iprot.readString();
              struct.setAuthSessionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CreatePinCodeRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.authSessionId != null) {
        oprot.writeFieldBegin(AUTH_SESSION_ID_FIELD_DESC);
        oprot.writeString(struct.authSessionId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CreatePinCodeRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CreatePinCodeRequestTupleScheme getScheme() {
      return new CreatePinCodeRequestTupleScheme();
    }
  }

  private static class CreatePinCodeRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<CreatePinCodeRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CreatePinCodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAuthSessionId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAuthSessionId()) {
        oprot.writeString(struct.authSessionId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CreatePinCodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.authSessionId = iprot.readString();
        struct.setAuthSessionIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

