/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-05-20")
public enum ErrorCode implements org.apache.thrift.TEnum {
  INTERNAL_ERROR(0),
  ILLEGAL_ARGUMENT(1),
  VERIFICATION_FAILED(2),
  NOT_ALLOWED_QR_CODE_LOGIN(3),
  VERIFICATION_NOTICE_FAILED(4),
  RETRY_LATER(5),
  INVALID_CONTEXT(100),
  APP_UPGRADE_REQUIRED(101);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return INTERNAL_ERROR;
      case 1:
        return ILLEGAL_ARGUMENT;
      case 2:
        return VERIFICATION_FAILED;
      case 3:
        return NOT_ALLOWED_QR_CODE_LOGIN;
      case 4:
        return VERIFICATION_NOTICE_FAILED;
      case 5:
        return RETRY_LATER;
      case 100:
        return INVALID_CONTEXT;
      case 101:
        return APP_UPGRADE_REQUIRED;
      default:
        return null;
    }
  }
}
